-- FUNÇÃO QUE RETORNA A QUANTIDADE DE CIDADE AGRUPADA POR ESTADO
CREATE OR REPLACE FUNCTION FNC_QTD_CIDADE_POR_ESTADO
(P_CD_ESTADO LOC_ESTADO.CD_ESTADO%TYPE) RETURN NUMBER IS
  
  CURSOR C_CIDADES(PR_CD_ESTADO LOC_ESTADO.CD_ESTADO%TYPE) IS SELECT E.CD_ESTADO, COUNT(C.CD_CIDADE) AS 
  QTD FROM LOC_CIDADE C JOIN LOC_ESTADO E 
  ON E.CD_ESTADO = C.CD_ESTADO WHERE C.CD_ESTADO = PR_CD_ESTADO GROUP BY E.CD_ESTADO;

  V_CIDADES C_CIDADES%ROWTYPE;
 
BEGIN
  OPEN C_CIDADES(P_CD_ESTADO);
  FETCH C_CIDADES INTO V_CIDADES;
  RETURN V_CIDADES.QTD;
  CLOSE C_CIDADES;
END;